"""Write text files with a header recording how they were generated."""
import datetime
import getpass
import os
import platform
import sys

import numpy as np


def savetxt(file_name, array, header=None, fmt='%.5f'):
    """Save array with np.savetxt, adding script, arguments, date and user."""
    date = datetime.datetime.now().isoformat(sep=' ', timespec='seconds')
    header_comment = (
        f'This file was generated by {os.path.abspath(sys.argv[0])}:\n'
        f'{" ".join(sys.argv)}\n\n'
        f'{date}, {getpass.getuser()}@{platform.node()}'
    )
    if header:
        header_comment += f'\n{header}'
    np.savetxt(file_name, array, fmt=fmt, header=header_comment)
